#!/system/bin/sh
# Init.d test

if [ -f /data/Test.log ] ; then
    rm /data/Test.log
fi

echo "Init.d is working !!!" >> /data/Test.log
echo "excecuted on $(date +"%d-%m-%Y %r" )" >> /data/Test.log

